### ISSUE TITLE
camera stream not work

### ISSUE THREAD

**Issue by qulet** [chillibasket/walle-replica#27]
http://192.168.1.25:8080/?action=stream not work
![camera_not_work](https://user-images.githubusercontent.com/30979927/226567506-a357bbae-f253-4af5-8eea-39cb02d4c508.jpg)
![wall-e_](https://user-images.githubusercontent.com/30979927/226567910-9856fa75-8b05-4093-8994-bd7ee094fe4f.jpg)

**Comment by qulet** [comment]
Wall-e works fine. The problem is no preview from the raspberry pi camera. I ran the mjpg-streamer.sh script with a resolution of 800x600 also does not work. Please help me solve this problem.
On the website http://192.168.1.25:8080/action=stream
  no picture.
in the terminal window
libcamera-hello -t 0
the camera is working properly

**Comment by qulet** [comment]
Miałem uszkodzoną taśmę.....:(((
Na stronie https://wired.chillibasket.com/3d-printed-wall-e/ komentowanie nie działa....

{"code":"wc_invalid_field"}

I want to THANK chilibasket VERY MUCH for sharing a great project. I changed some electronics. I used arduino Nano and replaced PIN13 with PIN 7. I used the L293_v1_red module to drive the motors, and rasbperry Pi 4 with a camera for the WWW interface.

I have a question for the creator of the virtual joystick software.

Is it possible for Wall-E to drive backwards?

**Comment by chillibasket** [comment]
Thank you for pointing out that comments on my website were no longer working, I have fixed the issue now. I'm happy to hear you resolved the camera issue. Yes the virtual joystick can send commands to drive the Wall-E backwards, which should make the motors spin backwards. I'm not sure if there are any differences in the motor driver you are using.

On my Wall-E I find the the tracks often lock-up when trying to drive backwards, which is probably because my original design does not include track tensioning. When I pick up the Wall-E off the ground to remove the load, the tracks spin backwards properly.

**Comment by qulet** [comment]
Thank you very much again for sharing  Wall-E project and contact. I used arduino nano and in the original control file I replaced:

/// Define pin-mapping
// -- -- -- -- -- -- -- -- -- -- -- -- -- --
#define DIRECTION_L_PIN 12 // Motor direction pins
#define DIRECTION_R_PIN 7 // HERE WAS PIN 13
#define PWM_SPEED_L_PIN 3 // Motor PWM pins
#define PWM_SPEED_R_PIN 11
#define BRAKE_L_PIN 9 // Motor brake pins
#define BRAKE_R_PIN 8
#define SERVO_ENABLE_PIN 10 // Servo shield output enable pin

In Nano there is a BLIK diode on pin 13, maybe you need to change something in the code?  (sorry, I'm not fully coding...)  As I wrote earlier, the motors work properly, the forward movement to the right and left with PWM acceleration works properly.

**Comment by qulet** [comment]
I forgot to add that I have a version with track tensioning bearings.
